#!/bin/bash
#
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=168:00:00
#SBATCH --mem=16GB
#SBATCH --array=1-17
#SBATCH --job-name=CLPM_general_sort
#SBATCH --mail-type=ALL
#SBATCH --mail-user=wj2068@nyu.edu
# env. variable SLURM_ARRAY_TASK_ID will be available

module purge
module load r/gcc/4.3.1
cd /scratch/wj2068/precarious
R -q -f CLPM_general_sort_industry.R